use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# RobiWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :robi, RobiWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 4002],
  url: [scheme: "https", host: "robi.stephanerobino.com"],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: "GhBurMwunRGjFtGKvPd/3rjZxHhB64gkFkmv973Sa4wWuclw2LT0GMTe1Hd7il44",
  server: true

# Do not print debug messages in production
config :logger, level: :info
